### ISSUE TITLE
How to configure ldflags in PlatformIO 

### ISSUE THREAD

**Issue by lidonglei1** [tanakamasayuki/aquestalk#1]
hi，
Nice work！
I have run this library in arduino，and I want use  this library in PlatformIO.
Could you tell me how to How to configure the compiler.libraries.ldflags in PlatformIO.
Thank you.

**Comment by tanakamasayuki** [comment]
Aquestalk is a paid product for Japanese people, so I don't recommend it.
We recommend using a cloud service such as Google TTS.

**Comment by lidonglei1** [comment]
> Aquestalk is a paid product for Japanese people, so I don't recommend it. We recommend using a cloud service such as Google TTS.

I got it. I know these and Japanese is also okay. And I need an offline TTS like this project.

**Comment by tanakamasayuki** [comment]
https://qiita.com/watarukato/items/6fe61a9c3568a3b6c16d

There is some information here, in Japanese.

**Comment by lidonglei1** [comment]
> https://qiita.com/watarukato/items/6fe61a9c3568a3b6c16d
> 
> There is some information here, in Japanese.

I got it.Thank you very much.
